### PR TITLE
feat: allow multifile yaml

### PR DESCRIPTION
**Pull request by holzgeist**
related to fjogeleit/yaml-update-action#532

It allows to modify multifile yaml files, separated by `---`.
If the input is a multifile, the value_path needs to start with an index, e.g. `[0].path.to.value` if the value should be changed in the first file

I'm not sure how to remove the ` as unknown as ...` casts, my TypeScript is too rusty for this.
`ContentNode` has `ContentNode[]` in its definition, so I feel like this is supposed to work, but it doesn't.

### CODE REVIEW

**Comment by fjogeleit** [comment]
Hey, thanks I will take a look over the weekend.

**Comment by holzgeist** [comment]
Hi,
Looks like I didn't test thoroughly enough. The resulting output is a YAML array, not a multifile.. 
Not sure how to handle this properly. I would need to return/remember if the input was multifile or not and pass that as dump option. Simply converting every top-level array into a multifile won't do ;)

Option 1: Not only return the parsed data, but also some options/flags that need to be passed to the dump invocation
Option 2: Convert the parser into actual classes, instantiate it and remember if the input was multifile during parsing and use this information during dumping

Option 2 would make more sense IMHO.

WDYT?

**Comment by fjogeleit** [comment]
You can try a class with some state but not that also the combinations of multifile and multiple changes should work. I know thats not that easy to achieve, thats one of the reason I do not implement this feature yet

**Comment by holzgeist** [comment]
@fjogeleit does the new test `multiple changes in multiple files, including multifiles` do what you asked?

**Comment by fjogeleit** [comment]
Hey @holzgeist, I am on a conference this week but will check it out next week.

can you check the codestyle checks?

the missing pr stuff is probably not working correctly. Will check the tests manually.

looks good in the first place, thanks

**Comment by holzgeist** [comment]
Thanks!

I ran prettier, tests and co. now. Hopefully it works

I even added some documentation to the readme :smile:

**Comment by fjogeleit** [comment]
thanks for your work

**Pull request merged**
